version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laramailchimp
    container_name: laramailchimp-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laramailchimp

  db:
    image: mysql:5.7
    container_name: laramailchimp-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "laramailchimp"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_USER: "root"
    ports:
      - "3306:3306"
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - laramailchimp

  nginx:
    image: nginx:alpine
    container_name: laramailchimp-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - laramailchimp

networks:
  laramailchimp:
    driver: bridge
